-- CRIAÇAÕ DE BANCO DE DADOS

IF DB_ID('FilmesDb') IS NOT NULL
	DROP DATABASE FilmesDb;

CREATE DATABASE FilmesDb;

USE FilmesDb;

-- CRIAÇÃO TABELA Generos
CREATE TABLE Generos(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Genero VARCHAR(20) NULL
);

-- CRIAÇÃO TABELA Atores
CREATE TABLE Atores(
	Id INT IDENTITY(1,1) 	PRIMARY KEY,
	PrimeiroNome 			VARCHAR(20) NOT NULL,
	UltimoNome 				VARCHAR(20) NOT NULL,
	Genero 					CHAR(1) 	NOT NULL
)

-- CRIAR TABELA FILMES
CREATE TABLE Filmes(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Ano INT NOT NULL,
	Duracao INT NOT NULL
)

-- CRIAÇÃO DA TABELA DE LIGACAO FilmesGenero (MUITOS PARA MUITOS FILMES <> GENEROS)
CREATE TABLE FilmesGenero(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdGenero INT NOT NULL,
	IdFilme INT NOT NULL,
	CONSTRAINT FK_FilmesGenero_Generos FOREIGN KEY (IdGenero) REFERENCES Generos(Id),
	CONSTRAINT FK_filmesGenero_Filmes  FOREIGN KEY (IdFilme)  REFERENCES Filmes(Id)
)

-- CRIAR TABELA ELENCOFILMES
CREATE TABLE ElencoFilme(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdAtor INT NOT NULL,
	IdFilme INT NOT NULL,
	Papel VARCHAR(30) NOT NULL,
	CONSTRAINT FK_ElencoFilme_Atores FOREIGN KEY(IdAtor) REFERENCES 	Atores(Id),
	CONSTRAINT FK_ElencoFilme_Filmes FOREIGN KEY(IdFilme) REFERENCES	Filmes(Id) 
)
